<?php

namespace Nemundo\Db\Provider\MySql\Data;


use Nemundo\Core\Csv\Writer\CsvWriter;
use Nemundo\Core\File\Path;
use Nemundo\Core\File\UniqueFilename;
use Nemundo\Project\ProjectConfig;


// mit ausgelagertem Csv???
class MySqlLoadData extends AbstractMySqlLoadData   // AbstractDbBase
{

    /**
     * @var CsvWriter
     */
    private $csvWriter;


    public function __construct()
    {

        parent::__construct();
        //$this->fieldNameList = new FieldNameList();

        $this->csvFilename = (new Path())
            ->addPath(ProjectConfig::$tmpPath)
            ->addPath((new UniqueFilename())->getUniqueFilename('csv'))
            ->getFilename();

        $this->csvWriter = new CsvWriter($this->csvFilename);


    }


    public function addData($valueList)
    {

        $this->csvWriter->addRow($valueList);

    }


    public function importData()
    {
        $this->csvWriter->closeFile();
        parent::importData(); // TODO: Change the autogenerated stub
    }

}